const U='https://fptdqutdzcxhrponaykv.supabase.co',K='sb_publishable_9XabgkDoLtPygEol6hPM8w_Dq9qRBPy',$=x=>document.getElementById(x),S={p:[],pr:{},k:[],buy:[],teams:[],sc:[],generated:[],saved:[],genVersion:0,set:{league_size:12,team_budget:200,roster_spots:14}};
async function req(table,opt={}){let qs=new URLSearchParams(opt.q||{}),r=await fetch(U+'/rest/v1/'+table+(qs.toString()?'?'+qs:''),{method:opt.m||'GET',headers:{apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json',Prefer:opt.prefer||'return=representation'},body:opt.body?JSON.stringify(opt.body):undefined}),txt=await r.text(),d=txt?JSON.parse(txt):null;if(!r.ok)throw Error(d.message||txt);return d}
const money=n=>'$'+Math.round(+n||0),pref=id=>S.pr[id]||{liked:false,target:false},keeper=id=>S.k.find(x=>x.player_id===id),sold=id=>S.buy.find(x=>x.player_id===id),avail=p=>!keeper(p.id)&&!sold(p.id),pd=p=>({ffb:p.ffb_value,fp:p.fp_value,blend:+p.blended_value||1,up:+p.upside||0});
function kval(){return S.k.reduce((a,x)=>{let p=S.p.find(z=>z.id===x.player_id);return a+(p?pd(p).blend:0)},0)}function kcost(){return S.k.reduce((a,x)=>a+(+x.cost||0),0)}function infl(){let total=2400,v=kval(),c=kcost();return Math.max(.85,Math.min(1.6,(total-c)/Math.max(1,total-v)))}function market(p){return Math.max(1,pd(p).blend*infl())}
function teamAssets(name){const ks=S.k.filter(x=>x.team_name===name).map(x=>({player_id:x.player_id,cost:+x.cost||0})),bs=S.buy.filter(x=>x.buyer===name).map(x=>({player_id:x.player_id,cost:+x.cost||0}));return ks.concat(bs)}function teamSummary(name){const a=teamAssets(name),c={QB:0,RB:0,WR:0,TE:0,K:0,DST:0};a.forEach(x=>{let p=S.p.find(z=>z.id===x.player_id);if(p)c[p.position]=(c[p.position]||0)+1});let spent=a.reduce((s,x)=>s+x.cost,0);return{spent,remaining:200-spent,roster:a.length,c}}function mine(){let a=S.k.filter(x=>x.team_name.toLowerCase()==='cody').map(x=>({id:x.player_id,c:+x.cost,k:1}));return a.concat(S.buy.filter(x=>x.is_mine).map(x=>({id:x.player_id,c:+x.cost,k:0})))}function budget(){let a=mine(),spent=a.reduce((s,x)=>s+x.c,0),slots=14-a.length,rem=200-spent;return{spent,slots,rem,max:slots?rem-(slots-1):0}}
function counts(){let c={QB:0,RB:0,WR:0,TE:0,K:0,DST:0};mine().forEach(a=>{let p=S.p.find(x=>x.id===a.id);if(p)c[p.position]++});return c}
function demand(pos){return{QB:12,RB:31,WR:43,TE:14,K:12,DST:12}[pos]||0}function removed(pos){return S.k.filter(x=>S.p.find(p=>p.id===x.player_id)?.position===pos).length+S.buy.filter(x=>S.p.find(p=>p.id===x.player_id)?.position===pos).length}
function scarcity(pos){if(['K','DST'].includes(pos))return{lvl:'LOW',pct:0,ratio:0,supply:99};let floor=pos==='QB'?3:pos==='TE'?4:7,supply=S.p.filter(p=>avail(p)&&p.position===pos&&market(p)>=floor).length,ratio=Math.max(0,demand(pos)-removed(pos))/Math.max(1,supply),pct=0,lvl='LOW';if(ratio>=1.05){pct=.14;lvl='HIGH'}else if(ratio>=.78){pct=.09;lvl='RISING'}else if(ratio>=.58){pct=.05;lvl='WATCH'}return{lvl,pct,ratio,supply}}function target(p){return market(p)*(1+scarcity(p.position).pct)}
function need(p){let c=counts();if(p.position==='QB')return c.QB<1?18:-8;if(p.position==='RB')return c.RB<2?24:c.RB<4?12:3;if(p.position==='WR')return c.WR<3?24:c.WR<5?13:4;if(p.position==='TE')return c.TE<1?16:0;return mine().length>=11?2:-15}
function flyerScore(p){if(['K','DST'].includes(p.position)||!avail(p))return 0;let price=liveBid(p),up=pd(p).up||0,r=pref(p.id);let cheap=Math.max(0,16-price)*3;let mid=Math.max(0,28-price)*.8;let ceiling=up*7;let prefBoost=r.target?16:r.liked?8:0;let scarcityPenalty=scarcity(p.position).pct*12;return cheap+mid+ceiling+prefBoost-scarcityPenalty}
function isFlyer(p){let price=liveBid(p),up=pd(p).up||0;return avail(p)&&!['K','DST'].includes(p.position)&&price<=18&&flyerScore(p)>=45&&(up>=5||pref(p.id).liked||pref(p.id).target)}
function pri(p){let x=target(p)+need(p)+scarcity(p.position).pct*40,r=pref(p.id);if(r.target)x+=24;else if(r.liked)x+=14;x+=pd(p).up*1.3;return x}
function renderMoney(){let b=budget(),myk=S.k.filter(x=>x.team_name.toLowerCase()==='cody'),val=myk.reduce((a,x)=>{let p=S.p.find(z=>z.id===x.player_id);return a+(p?pd(p).blend:0)},0),cost=myk.reduce((a,x)=>a+(+x.cost||0),0);$('money').innerHTML=[['Starting','$200'],['Keeper spend',money(cost)],['Remaining',money(b.rem)],['Keeper surplus','+'+money(val-cost)],['Market inflation',((infl()-1)*100).toFixed(1)+'%']].map(x=>`<div class=stat><span class=sm>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function slots(){let assets=mine().map(a=>({...a,p:S.p.find(x=>x.id===a.id)})).filter(x=>x.p),names=['QB','RB','RB','WR','WR','WR','TE','FLEX','K','DST','BENCH','BENCH','BENCH','BENCH'],used=new Set;return names.map(s=>{let i=assets.findIndex((a,j)=>!used.has(j)&&(s==='FLEX'?['RB','WR','TE'].includes(a.p.position):s==='BENCH'?true:a.p.position===s));if(i>=0)used.add(i);return{s,a:i>=0?assets[i]:null}})}
function renderSlots(){$('slots').innerHTML=slots().map(x=>`<div class="slot ${x.a?'f':''}"><span class=sm>${x.s}</span><div><b>${x.a?x.a.p.name:'—'}</b></div>${x.a?`<span class=sm>${money(x.a.c)}</span>`:''}</div>`).join('')}
function renderScarcity(){$('scarcity').innerHTML=['RB','WR','TE','QB'].map(pos=>{let s=scarcity(pos),cl=s.lvl==='HIGH'?'r':s.lvl==='LOW'?'g':'y',w=Math.min(100,s.ratio*80);return`<div class="sc ${cl}"><div class=line><b>${pos}</b><b>${s.lvl}</b></div><div class=sm>${s.supply} viable options left</div><div class=scbar><i style="width:${w}%"></i></div></div>`}).join('')}
function row(p){let d=pd(p),r=pref(p.id),k=keeper(p.id),b=sold(p.id),state=k?'KEEPER':b?(b.is_mine?'MINE':'SOLD'):'AVAILABLE';return`<tr class="${r.liked?'like ':''}${r.target?'target ':''}${isFlyer(p)?'flyer':''}"><td><b>${p.name}</b>${isFlyer(p)?'<span class=flyerbadge>UPSIDE FLYER</span>':''}<div class=sm>${p.team||''}</div></td><td>${p.position}</td><td>${d.ffb==null?'—':money(d.ffb)}</td><td>${d.fp==null?'—':money(d.fp)}</td><td>${money(d.blend)}</td><td>${money(market(p))}</td><td class="price ${scarcity(p.position).lvl==='HIGH'?'r':'y'}">${money(target(p))}<div class=sm>${scarcity(p.position).lvl}</div></td><td><button class=rowbtn onclick="like(${p.id})">${r.liked?'✓ Like':'Like'}</button> <button class=rowbtn onclick="tar(${p.id})">${r.target?'★ Target':'Target'}</button></td><td>${state==='AVAILABLE'?`<button class=rowbtn onclick="buy(${p.id},1)">Mine</button> <button class=rowbtn onclick="buy(${p.id},0)">Gone</button>`:`${state} ${money(k?k.cost:b.cost)}`}</td></tr>`}
function renderBoard(){let ps=[...S.p],q=$('q').value.toLowerCase(),pos=$('pos').value,v=$('view').value;if(q)ps=ps.filter(p=>p.name.toLowerCase().includes(q));if(pos!=='ALL')ps=ps.filter(p=>p.position===pos);if(v==='available')ps=ps.filter(avail);if(v==='liked')ps=ps.filter(p=>pref(p.id).liked);if(v==='targets')ps=ps.filter(p=>pref(p.id).target);if(v==='flyers')ps=ps.filter(isFlyer);ps.sort((a,b)=>target(b)-target(a));$('rows').innerHTML=ps.map(row).join('')}
function renderFlyers(){let ps=S.p.filter(isFlyer).sort((a,b)=>flyerScore(b)-flyerScore(a)).slice(0,8);$('flyers').innerHTML=ps.length?ps.map(p=>`<div class=line><span><b>${p.name}</b><div class=sm>${p.position} · score ${Math.round(flyerScore(p))} · upside ${pd(p).up||'—'}</div></span><b class=g>${money(liveBid(p))}</b></div>`).join(''):'<div class=sm>No strong low-cost flyers at the current room prices.</div>'}
function renderBest(){let ps=S.p.filter(avail).sort((a,b)=>pri(b)-pri(a)).slice(0,7);$('best').innerHTML=ps.map(p=>`<div class=line><span><b>${p.name}</b><div class=sm>${p.position} · ${scarcity(p.position).lvl}</div></span><b>${money(target(p))}</b></div>`).join('')}
function eligible(p,s){return s==='FLEX'?['RB','WR','TE'].includes(p.position):s==='BENCH'?['QB','RB','WR','TE'].includes(p.position):p.position===s}
function genSlots(){let c=counts(),ss=[];if(c.QB<1)ss.push('QB');for(let i=c.RB;i<2;i++)ss.push('RB');for(let i=c.WR;i<3;i++)ss.push('WR');if(c.TE<1)ss.push('TE');ss.push('FLEX');if(c.K<1)ss.push('K');if(c.DST<1)ss.push('DST');while(ss.length<budget().slots)ss.push('BENCH');return ss;}