function buildGenContext(){
 const infNow=infl(),bud=budget(),slots=genSlots(),availPlayers=S.p.filter(avail),room={};
 ['QB','RB','WR','TE','K','DST'].forEach(pos=>{
   let teams=S.teams.filter(x=>!x.is_mine),need=0,cash=0;
   teams.forEach(tm=>{let s=teamSummary(tm.name),n=pos==='QB'?s.c.QB<1:pos==='RB'?s.c.RB<2:pos==='WR'?s.c.WR<3:pos==='TE'?s.c.TE<1:false;if(n){need++;cash+=s.remaining}});
   room[pos]={teams:need,cash,score:need?Math.min(1.5,(need/11)+(cash/2200)):0};
 });
 const removedByPos={};
 ['QB','RB','WR','TE','K','DST'].forEach(pos=>removedByPos[pos]=removed(pos));
 const supply={};
 ['QB','RB','WR','TE','K','DST'].forEach(pos=>{let floor=pos==='QB'?3:pos==='TE'?4:['K','DST'].includes(pos)?0:7;supply[pos]=availPlayers.filter(p=>p.position===pos&&Math.max(1,pd(p).blend*infNow)>=floor).length;});
 const sc={};
 ['QB','RB','WR','TE','K','DST'].forEach(pos=>{if(['K','DST'].includes(pos)){sc[pos]={lvl:'LOW',pct:0,ratio:0,supply:99};return}let ratio=Math.max(0,demand(pos)-removedByPos[pos])/Math.max(1,supply[pos]),pct=0,lvl='LOW';if(ratio>=1.05){pct=.14;lvl='HIGH'} else if(ratio>=.78){pct=.09;lvl='RISING'} else if(ratio>=.58){pct=.05;lvl='WATCH'}sc[pos]={lvl,pct,ratio,supply:supply[pos]};});
 const byId=new Map();
 availPlayers.forEach(p=>{let d=pd(p),m=Math.max(1,d.blend*infNow),roomP=room[p.position]||{score:0},scar=sc[p.position]||{pct:0,lvl:'LOW'},baseTarget=m*(1+scar.pct),live=Math.max(1,baseTarget*(1+Math.min(.12,roomP.score*.07))),r=pref(p.id);byId.set(p.id,{m,target:baseTarget,live,scar,room:roomP,up:d.up||0,liked:!!r.liked,targeted:!!r.target});});
 return {infNow,bud,slots,availPlayers,room,sc,byId};
}
function roomPressure(pos){let teams=S.teams.filter(x=>!x.is_mine),need=0,cash=0;teams.forEach(tm=>{let s=teamSummary(tm.name),n=pos==='QB'?s.c.QB<1:pos==='RB'?s.c.RB<2:pos==='WR'?s.c.WR<3:pos==='TE'?s.c.TE<1:false;if(n){need++;cash+=s.remaining}});return {teams:need,cash,score:need?Math.min(1.5,(need/11)+(cash/2200)):0};}
function liveBid(p){let sc=scarcity(p.position),rp=roomPressure(p.position);return Math.max(1,target(p)*(1+Math.min(.12,rp.score*.07)));}
function styleFor(i,selected){if(selected!=='mixed')return selected;return ['stars','balanced','depth','scarcity'][i%4]}
function rng(seed){let x=Math.sin(seed*999.91+17.33)*43758.5453;return x-Math.floor(x)}
function cachedPrice(meta,risk,seed,id){let jitter=rng(seed+id*.317)-.5,mult=risk==='aggressive'?1.05+jitter*.16:risk==='conservative'?.92+jitter*.10:.98+jitter*.14;return Math.max(1,Math.round(meta.live*mult));}
function cachedCandidateScore(p,meta,style,slot,seed){let base=meta.live+need(p)+meta.scar.pct*40+(rng(seed+p.id*1.713)-.5)*18;if(meta.targeted)base+=28;else if(meta.liked)base+=14;base+=meta.up*1.3;if(style==='stars')base+=meta.live*.72;if(style==='balanced')base+=Math.max(0,26-Math.abs(meta.live-17))*1.1;if(style==='depth')base+=Math.max(0,20-meta.live)*1.45+meta.up*1.2;if(style==='scarcity')base+=meta.scar.pct*95+meta.room.score*28;if(slot==='BENCH')base+=Math.max(0,13-meta.live)*1.15+meta.up+Math.max(0,18-meta.live)*.9;return base;}
function buildScenarioFast(ctx,style,risk,seed,forcedId){let slots=[...ctx.slots],B=ctx.bud.rem,used=new Set,out=[],spent=0;if(forcedId){let fp=ctx.availPlayers.find(p=>p.id===+forcedId),fm=fp&&ctx.byId.get(fp.id);if(fp&&fm){let idx=slots.findIndex(s=>eligible(fp,s));if(idx>=0){let pr=cachedPrice(fm,risk,seed+91,fp.id),reserve=slots.length-1;if(pr<=B-reserve){out.push({s:slots[idx],p:fp,pr});used.add(fp.id);spent+=pr;slots.splice(idx,1)}}}}for(let i=0;i<slots.length;i++){let slot=slots[i],reserve=slots.length-i-1,max=Math.max(1,B-spent-reserve),cand=[];for(const p of ctx.availPlayers){if(used.has(p.id)||!eligible(p,slot))continue;let meta=ctx.byId.get(p.id),pr=cachedPrice(meta,risk,seed+i*17,p.id);if(pr>max)continue;cand.push({p,pr,sc:cachedCandidateScore(p,meta,style,slot,seed+i*31)});}cand.sort((a,b)=>(slot==='K'||slot==='DST')?a.pr-b.pr:b.sc-a.sc);let lim=Math.min(8,cand.length),choice=lim?cand[Math.floor(rng(seed+i*43)*lim)]:null;if(choice){used.add(choice.p.id);out.push({s:slot,p:choice.p,pr:choice.pr});spent+=choice.pr}}let likes=0,upside=0,value=0,scarcityHit=0;out.forEach(x=>{let m=ctx.byId.get(x.p.id);if(m.liked||m.targeted)likes++;upside+=m.up;value+=m.live-x.pr;scarcityHit+=m.scar.pct*10});let complete=out.length===ctx.bud.slots,left=B-spent,score=(complete?120:0)+likes*9+upside*1.8+value*2+scarcityHit-left*.2;return {style,risk,out,spent,left,score,likes,upside,value,complete,key:out.map(x=>x.p.id).sort((a,b)=>a-b).join('-')};}
async function generateMany(){if(!S.p.length){$('genMeta').textContent='Player pool is still loading.';return}const btn=$('gen'),count=+$('genCount').value||50,sel=$('genStyle').value,risk=$('genRisk').value,forced=$('mustInclude').value,ctx=buildGenContext();btn.disabled=true;btn.classList.add('loading');btn.innerHTML='<span class="spin" aria-hidden="true"></span><span>Generating…</span>';S.generated=[];$('builds').innerHTML='';let builds=[],seen=new Set(),attempts=Math.min(1800,count*14),seedBase=Date.now()%100000;$('genMeta').textContent=`Generating 0 / ${count} viable scenarios…`;for(let i=0;i<attempts&&builds.length<count;i++){let b=buildScenarioFast(ctx,styleFor(i,sel),risk,seedBase+i*97,forced);if(b.complete&&b.left>=0&&!seen.has(b.key)){seen.add(b.key);builds.push(b)}if(i%24===0){S.generated=[...builds].sort((a,b)=>b.score-a.score);$('genMeta').textContent=`Generating ${builds.length} / ${count} viable scenarios…`;renderBuilds();await new Promise(r=>setTimeout(r,0));}}S.generated=builds.sort((a,b)=>b.score-a.score);S.genVersion++;renderBuilds();$('genMeta').textContent=S.generated.length?`${S.generated.length} viable scenarios generated from the current room · showing top ${Math.min(30,S.generated.length)} · refreshes when the room changes`:'No complete viable scenarios found with these settings. Try Mixed strategies or Normal volatility.';btn.disabled=false;btn.classList.remove('loading');btn.textContent='Generate scenarios';}
function refreshGenerated(){if(!S.generated.length)return;let valid=S.generated.filter(b=>b.out.every(x=>avail(x.p))&&b.out.length===budget().slots);if(valid.length!==S.generated.length){S.generated=valid;renderBuilds();$('genMeta').textContent=`${valid.length} existing scenarios still valid after the latest room change. Generate again for fresh alternatives.`}}
function myKeeperRows(){return S.k.filter(x=>x.team_name.toLowerCase()==='cody').map(k=>({k,p:S.p.find(p=>p.id===k.player_id)})).filter(x=>x.p)}
function generatedPayload(b){return{style:b.style||'saved',risk:b.risk||'normal',score:+b.score||0,spent:+b.spent||0,left:+b.left||0,likes:+b.likes||0,value:+b.value||0,out:(b.out||[]).map(x=>({slot:x.s||x.slot||'—',player_id:x.p?.id||x.player_id,price:+(x.pr??x.price)||0}))}}
function payloadKey(b){return (b?.out||[]).map(x=>`${x.player_id}:${x.price}`).join('|')}
function generatedKey(b){return payloadKey(generatedPayload(b))}
function isSavedGenerated(b){let k=generatedKey(b);return (S.saved||[]).some(x=>payloadKey(x.build)===k)}