function renderBuilds(){
 let el=$('builds');
 if(!S.generated.length){el.innerHTML='<div class="sm">No generated scenarios yet. Click <b>Generate scenarios</b>.</div>';$('genMeta').textContent='';return}
 let top=S.generated.slice(0,30),keepers=myKeeperRows(),keeperSpend=keepers.reduce((a,x)=>a+(+x.k.cost||0),0);
 $('genMeta').textContent=`${S.generated.length} viable scenarios generated from the current room · showing top ${top.length} · auto-invalidates as players are sold`;
 el.innerHTML=top.map((b,i)=>{let totalSpend=keeperSpend+b.spent,totalLeft=200-totalSpend,saved=isSavedGenerated(b);return `<div class=build><div class=buildtop><div><span class=rankbadge>#${i+1}</span> <b>${b.style[0].toUpperCase()+b.style.slice(1)}</b><div class=scenarioTags><span class=tag>${b.likes} Likes/Targets</span><span class=tag>${money(b.value)} proj. value</span><span class=tag>${b.risk} bids</span><span class=tag>${keepers.length} keepers</span></div></div><div style="text-align:right"><div class=score>${Math.round(b.score)}</div><div class=sm>${money(totalSpend)} total spend · ${money(totalLeft)} left</div><div class=sm>${money(keeperSpend)} keepers + ${money(b.spent)} auction</div></div></div>${keepers.map(x=>`<div class=br><span class=sm>KEEPER</span><b>${x.p.name}</b><span>${x.p.position}</span><span class=g>${money(x.k.cost)}</span></div>`).join('')}${b.out.map(x=>`<div class=br><span class=sm>${x.s}</span><b>${x.p.name}</b><span>${x.p.position}</span><span class="${scarcity(x.p.position).lvl==='HIGH'?'r':scarcity(x.p.position).lvl==='LOW'?'g':'y'}">${money(x.pr)}</span></div>`).join('')}<div class=buildactions><button class=rowbtn onclick="loadBuildIndex(${i})">Load into builder</button><button class=rowbtn ${saved?'disabled':''} onclick="saveGeneratedBuild(${i})">${saved?'✓ Saved':'Save build'}</button></div></div>`}).join('')
}
function loadIntoBuilder(out,label){S.sc=(out||[]).map(x=>({id:+(x.p?.id||x.player_id),price:+(x.pr??x.price)||0})).filter(x=>x.id);renderScenario();$('genMeta').textContent=`${label} loaded into the builder below.`;let card=$('scenarioBuilderCard');if(card){card.style.boxShadow='0 0 0 2px var(--a)';card.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>card.style.boxShadow='',1400)}}
window.loadBuildIndex=i=>{let b=S.generated[i];if(!b)return;loadIntoBuilder(b.out,`Build #${i+1}`)}
window.saveGeneratedBuild=async i=>{let b=S.generated[i];if(!b)return;let payload=generatedPayload(b),key=payloadKey(payload);if((S.saved||[]).some(x=>payloadKey(x.build)===key)){renderBuilds();return}let name=`${b.style[0].toUpperCase()+b.style.slice(1)} #${i+1} · ${money(b.spent)} auction`;try{let d=await req('auction_saved_builds',{m:'POST',body:{name,build:payload}});if(d?.[0])S.saved=[d[0],...(S.saved||[])];renderBuilds();renderSavedBuilds();$('genMeta').textContent=`Saved ${name}.`}catch(e){$('genMeta').textContent='Save failed: '+e.message}}
function renderSavedBuilds(){let el=$('savedBuilds');if(!el)return;let rows=S.saved||[],keepers=myKeeperRows(),keeperSpend=keepers.reduce((a,x)=>a+(+x.k.cost||0),0);if(!rows.length){el.innerHTML='<div class="sm">No saved builds yet. Tap <b>Save build</b> on any generated scenario you want to keep.</div>';return}el.innerHTML=rows.map(r=>{let b=r.build||{},out=b.out||[],unavailable=out.filter(x=>{let p=S.p.find(z=>z.id===+x.player_id);return p&&!avail(p)}).length,total=keeperSpend+(+b.spent||out.reduce((a,x)=>a+(+x.price||0),0));return `<div class=build><div class=buildtop><div><b>${r.name||'Saved build'}</b><div class="sm savednote">${new Date(r.created_at).toLocaleString()}${unavailable?` · <span class=r>${unavailable} player${unavailable===1?'':'s'} no longer available</span>`:''}</div></div><div style="text-align:right"><div class=score>${Math.round(+b.score||0)}</div><div class=sm>${money(total)} total spend · ${money(200-total)} left</div></div></div>${keepers.map(x=>`<div class=br><span class=sm>KEEPER</span><b>${x.p.name}</b><span>${x.p.position}</span><span class=g>${money(x.k.cost)}</span></div>`).join('')}${out.map(x=>{let p=S.p.find(z=>z.id===+x.player_id);return p?`<div class=br><span class=sm>${x.slot||'—'}</span><b>${p.name}</b><span>${p.position}</span><span class="${avail(p)?'y':'r'}">${money(x.price)}</span></div>`:''}).join('')}<div class=buildactions><button class=rowbtn onclick="loadSavedBuild(${r.id})">Load into builder</button><button class=rowbtn onclick="deleteSavedBuild(${r.id})">Delete</button></div></div>`}).join('')}
window.loadSavedBuild=id=>{let r=(S.saved||[]).find(x=>+x.id===+id);if(!r)return;loadIntoBuilder(r.build?.out||[],r.name||'Saved build')}
window.deleteSavedBuild=async id=>{try{await req('auction_saved_builds',{m:'DELETE',q:{id:'eq.'+id}});S.saved=(S.saved||[]).filter(x=>+x.id!==+id);renderSavedBuilds();renderBuilds()}catch(e){$('genMeta').textContent='Delete failed: '+e.message}}
function renderScenario(){
 const available=S.p.filter(avail).sort((a,b)=>liveBid(b)-liveBid(a));
 $('sp').innerHTML=available.map(p=>`<option value=${p.id}>${p.name} · ${money(liveBid(p))}</option>`).join('');
 $('mustInclude').innerHTML='<option value="">No forced player</option>'+available.slice(0,180).map(p=>`<option value=${p.id}>Force: ${p.name} · ${money(liveBid(p))}</option>`).join('');
$('scenario').innerHTML=S.sc.map((x,i)=>{let p=S.p.find(z=>z.id===x.id);return`<div class=line><span><b>${p.name}</b><div class=sm>${p.position} · target ${money(target(p))}</div></span><span><input style="width:70px" type=number value=${x.price} onchange="S.sc[${i}].price=+this.value;renderScenario()"> <button class=rowbtn onclick="S.sc.splice(${i},1);renderScenario()">×</button></span></div>`}).join('');let cost=S.sc.reduce((a,x)=>a+x.price,0),b=budget(),left=b.rem-cost,slots=b.slots-S.sc.length;$('ssum').innerHTML=`<div class=line><span>Scenario spend</span><b>${money(cost)}</b></div><div class=line><span>Cash left</span><b>${money(left)}</b></div><div class=line><span>Slots left</span><b>${slots}</b></div>`;
 let needs=genSlots(),hot=['RB','WR','TE','QB'].map(p=>({p,s:scarcity(p),r:roomPressure(p)})).sort((a,b)=>(b.s.pct+b.r.score*.08)-(a.s.pct+a.r.score*.08)).slice(0,3);
 $('scenarioGuide').innerHTML=`<div class=line><span>Current max legal bid</span><b>${money(budget().max)}</b></div><div class=line><span>Hottest room pressure</span><b>${hot[0]?.p||'—'}</b></div>${hot.map(x=>`<div class="sc ${x.s.lvl==='HIGH'?'r':x.s.lvl==='LOW'?'g':'y'}"><b>${x.p}: ${x.s.lvl}</b><div class=sm>${x.r.teams} other teams still need starter help · ${x.s.supply} viable options left</div></div>`).join('')}`;
}
function renderKeepers(){$('kt').innerHTML=S.teams.map(x=>`<option value="${x.name}">${x.name}</option>`).join('');$('kp').innerHTML=S.p.filter(p=>!keeper(p.id)).sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value=${p.id}>${p.name}</option>`).join('');$('kl').innerHTML=S.k.sort((a,b)=>a.team_name.localeCompare(b.team_name)).map(k=>{let p=S.p.find(x=>x.id===k.player_id);return`<div class=keeper><span><b>${p?p.name:'?'}</b><div class=sm>${k.team_name}</div></span><b>${money(k.cost)}</b><button class=rowbtn onclick="remK(${k.id})">Remove</button></div>`}).join('')}
function renderRoom(){$('roomGrid').innerHTML=S.teams.map(tm=>{let s=teamSummary(tm.name),needs=[];if(s.c.QB<1)needs.push('QB');if(s.c.RB<2)needs.push('RB');if(s.c.WR<3)needs.push('WR');if(s.c.TE<1)needs.push('TE');let assets=teamAssets(tm.name).map(a=>{let p=S.p.find(x=>x.id===a.player_id);return p?`${p.name} ${money(a.cost)}`:''}).filter(Boolean);return `<div class="roomteam ${tm.is_mine?'mine':''}"><div class=line><b>${tm.name}</b><b>${money(s.remaining)} left</b></div><div class=sm>${s.roster}/14 rostered · ${money(s.spent)} spent</div><div class=chips><span class=chip>QB ${s.c.QB}</span><span class=chip>RB ${s.c.RB}</span><span class=chip>WR ${s.c.WR}</span><span class=chip>TE ${s.c.TE}</span></div><div class="sm y" style="margin-top:6px">${needs.length?'Needs: '+needs.join(', '):'Core starters filled'}</div><div class=sm style="margin-top:6px">${assets.length?assets.join(' · '):'No players assigned yet'}</div></div>`}).join('')}function render(){renderMoney();renderSlots();renderScarcity();renderBoard();renderFlyers();renderBest();renderScenario();renderKeepers();renderRoom();refreshGenerated();renderBuilds();renderSavedBuilds()}
async function like(id){let r=pref(id),v=!r.liked;await req('auction_preferences',{m:'POST',prefer:'resolution=merge-duplicates,return=representation',body:{player_id:id,liked:v,target:r.target,updated_at:new Date().toISOString()}});S.pr[id]={...r,liked:v};render()}
async function tar(id){let r=pref(id),v=!r.target;await req('auction_preferences',{m:'POST',prefer:'resolution=merge-duplicates,return=representation',body:{player_id:id,liked:r.liked,target:v,updated_at:new Date().toISOString()}});S.pr[id]={...r,target:v};render()}
async function buy(id,m){let p=S.p.find(x=>x.id===id),cost=prompt('Price paid for '+p.name+'?',Math.round(target(p)));if(cost===null)return;let buyer='Cody';if(!m){let names=S.teams.filter(x=>!x.is_mine).map(x=>x.name),pick=prompt('Buyer team number:\n'+names.map((n,i)=>(i+1)+'. '+n).join('\n'),'1');if(pick===null)return;buyer=names[Math.max(0,Math.min(names.length-1,(+pick||1)-1))]}let body={player_id:id,buyer,cost:+cost||0,is_mine:!!m,updated_at:new Date().toISOString()};await req('auction_purchases',{m:'POST',prefer:'resolution=merge-duplicates,return=representation',body});S.buy=S.buy.filter(x=>x.player_id!==id).concat([body]);render()}
async function remK(id){await req('auction_keepers',{m:'DELETE',q:{id:'eq.'+id}});S.k=S.k.filter(x=>x.id!==id);render()}
$('kadd').onclick=async()=>{let body={team_name:$('kt').value||'Other',player_id:+$('kp').value,cost:+$('kc').value||0,updated_at:new Date().toISOString()},d=await req('auction_keepers',{m:'POST',body});S.k.push(d[0]);render()};$('gen').onclick=generateMany;$('sadd').onclick=()=>{let id=+$('sp').value;if(!S.sc.some(x=>x.id===id))S.sc.push({id,price:+$('sprice').value||1});renderScenario()};$('sclear').onclick=()=>{S.sc=[];renderScenario()};['q','pos','view'].forEach(x=>$(x).addEventListener(x==='q'?'input':'change',renderBoard));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));['board','scenarios','keepers','room'].forEach(x=>$(x+'Tab').classList.toggle('hidden',x!==b.dataset.tab))});
async function load(){try{let [p,pr,k,buy,set,teams,saved]=await Promise.all([req('auction_players',{q:{select:'*'}}),req('auction_preferences',{q:{select:'*'}}),req('auction_keepers',{q:{select:'*'}}),req('auction_purchases',{q:{select:'*'}}),req('auction_settings',{q:{select:'*',id:'eq.1'}}),req('auction_teams',{q:{select:'*'}}),req('auction_saved_builds',{q:{select:'*',order:'created_at.desc'}})]);S.p=p;pr.forEach(x=>S.pr[x.player_id]=x);S.k=k;S.buy=buy;S.saved=saved||[];S.teams=teams.sort((a,b)=>b.is_mine-a.is_mine||a.name.localeCompare(b.name));if(set[0])S.set=set[0];render();$('status').textContent=`Loaded ${S.p.length} players · 12-team league`;$('status').className='sm g'}catch(e){$('status').textContent='Load failed: '+e.message;$('status').className='sm r'}}
load();